name: Setup Rust
description: Sets up Rust and relevant toolchain components

inputs:
  components:
    description: Comma-separated list of components to be additionally installed for a new toolchain
    required: false
    default: clippy, rustfmt

runs:
  using: "composite"
  steps:
    - name: Rust Toolchain
      id: rust-toolchain
      uses: dtolnay/rust-toolchain@master
      if: steps.rustup-cache.outputs.cache-hit != 'true'
      with:
        components: ${{ inputs.components }}

    - name: Rust Dependency Cache
      uses: Swatinem/rust-cache@v2
      with:
        save-if: ${{ github.ref_name == 'develop' }}
        shared-key: "shared" # To allow reuse across jobs

    - name: Rust Compile Cache
      uses: mozilla-actions/sccache-action@v0.0.6

    - name: Rust Compile Cache Config
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
