name: Lint TOML
description: "Linter to enforce TOML style and conventions"

inputs:
  is_cargo:
    description: "Whether the root directory is a cargo project"
    default: "true"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install taplo
      shell: bash
      run: cargo install taplo-cli --locked

    - name: Run taplo-cli
      shell: bash
      run: taplo fmt --check

    - name: install cargo-sort
      if: ${{ inputs.is_cargo == 'true' }}
      shell: bash
      run: cargo install cargo-sort --locked

    - name: Run cargo-sort
      if: ${{ inputs.is_cargo == 'true' }}
      shell: bash
      run: cargo sort -wc
