name: Lint TOML
description: "Linter to enforce TOML style and conventions"

runs:
  using: "composite"
  steps:
    - name: Install taplo
      uses: taiki-e/install-action@055f5df8c3f65ea01cd41e9dc855becd88953486 # v2
      with:
        tool: taplo

    - name: Run taplo-cli
      shell: bash
      run: taplo fmt --check
