name: Lint TOML
description: "Linter to enforce TOML style and conventions"

runs:
  using: "composite"
  steps:
    - name: Install taplo
      uses: taiki-e/install-action@41049aa56687c35e0afa74eed4f09cec4f9afabf # v2
      with:
        tool: taplo

    - name: Run taplo-cli
      shell: bash
      run: taplo fmt --check
