name: "Setup Python UV"
description: "Toolchain setup for Python UV"

inputs:
  sync:
    description: "Sync the project"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.18"
        enable-cache: true

    - name: "Setup up Python"
      shell: bash
      run: uv python install

    - name: Install the project
      if: ${{ inputs.sync == 'true' }}
      shell: bash
      run: uv sync --all-extras --dev -v
      env:
        MATURIN_PEP517_USE_BASE_PYTHON: "true"
        # Keep this constant to avoid pyo3 invalidating itself
        PYO3_ENVIRONMENT_SIGNATURE: "cpython3"

    - name: Export Path
      shell: bash
      run: echo "PATH=$PATH" >> $GITHUB_ENV
